### ISSUE TITLE
Anwendungsfalldiagramm

### ISSUE THREAD

**Issue by Cavvar** [sweIhm-ws2018-19/skillproject-fr-31#14]

**Comment by Cavvar** [comment]
![Use-Case GuideLines](https://drive.google.com/file/d/1dn8YbshqLvMKZzHM46YGSXkbg1PQSctX/view?usp=sharing)

**Comment by Cavvar** [comment]
![usecasealexaskill](https://user-images.githubusercontent.com/3383908/48264512-0ba62f80-e42a-11e8-99a8-243a7b983136.jpg)

**Comment by SchredlAar** [comment]
Die Anwendungsfälle wurden aus dem Prototyp übernommen und in ein Diagramm überführt.

**Comment by SchredlAar** [comment]
Diagramm ok.
