### ISSUE TITLE
Beschreibung der Anwendungsfälle

### ISSUE THREAD

**Issue by Cavvar** [sweIhm-ws2018-19/skillproject-fr-31#15]
Die Anwendungsfallbeschreibungen werden mittels des Anwendungsfalldiagramms kreiert.

**Comment by SchredlAar** [comment]
[Anwendungsfallbeschreibungen.pdf](https://github.com/sweIhm-ws2018-19/skillproject-fr-31/files/2568526/Anwendungsfallbeschreibungen.pdf)

**Comment by SchredlAar** [comment]
Hier einmal meine Version der Anwendungsfallbeschreibungen.
Wäre zum Review bereit.
Änderungen und Ergänzungen sind gerne erwünscht.

**Comment by SchredlAar** [comment]
Hab das Sourcefile noch im dev-Branch hochgeladen

**Comment by Cavvar** [comment]
Mein Vorschlag für die grundlegende Struktur:
[Anwendungsfallbeschreibung.pdf](https://github.com/sweIhm-ws2018-19/skillproject-fr-31/files/2569397/Anwendungsfallbeschreibung.pdf)

Bitte füge die Sourcefile in Master ein oder merge

**Comment by SchredlAar** [comment]
Ja das sieht auch gut aus

**Comment by SchredlAar** [comment]
Hab das Source-File in Master eingefügt
