### ISSUE TITLE
Begrüßung (UC 1)

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#18]

**Comment by Cavvar** [comment]
| Name der User Story        | User Story           | Akzeptanzkriterien  |
| ------------- |:-------------:| -----:|
| Begrüßung (UC 1)    | Als Nutzer*in möchte ich zum Start die Information erhalten, ob eine Einrichtung bereits stattfand. Der Skill begrüßt den User abhängig von der vorhandenen Konfiguration und sagt zum Beispiel: “Guten Morgen <Vorname>”. | <ul><li>variierende Begrüßungen</li><li>Begrüßung gibt Hinweis auf Konfiguration</li></ul> |

**Comment by Cavvar** [comment]
Funktionalität wurde mittels Vorname eingeben/ausgeben geprüft
