### ISSUE TITLE
Ersteinrichtung Benutzerkonto (UC 2)

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#19]

**Comment by Cavvar** [comment]
|Name der User Story|  User Story | Akzeptanzkriterien|
|--|--|--|
|Ersteinrichtung Benutzerkonto (UC 2)  |  Als Nutzer*in möchte ich meine Adressdaten speichern können, sodass beim späteren Gebrauch mit geringem Aufwand ich die effektivste Route zum gewünschten Ziel erhalte.| <ul><li>Stabile Internetverbindung</li><li>Here-API/GPS-Signal steht zum Zeitpunkt der Einrichtung zur Verfügung</li></ul>|

**Comment by Cavvar** [comment]
Diese User Story beinhaltet die gesamte Einrichtung des Benutzerprofils. Wird demnach erst abgeschlossen, wenn auch die Einrichtung aller Elemente fertig ist.

**Comment by TobiasKuch** [comment]
![ersteinrichtung_benutzerkonto_uc2](https://user-images.githubusercontent.com/32924677/49219795-a57f4d80-f3d4-11e8-9598-f7b776afa53d.png)

**Comment by TobiasKuch** [comment]
![ersteinrichtung_benutzerkonto_uc2](https://user-images.githubusercontent.com/32924677/49220231-f8a5d000-f3d5-11e8-9b50-d48c6839c5dc.png)

**Comment by SchredlAar** [comment]
Erfüllt die Bedingungen von Sprint1
Sehr gut

**Comment by timobunghardt** [comment]
Momentan gibt es, wenn ich es richtig verstehe noch keine Möglichkeit beim erneuten Start der Anwendung eine neue Einrichtung zu fordern. Gerne würden wir hier die Möglichkeit integrieren dem Nutzer die Möglichkeit zu geben, auf die Frage : "Wo möchtest du hin ?" mit "Einrichtungsassistent" zu antworten und die hinterlegten Nutzerdaten überschreiben /eine neue Einrichtung starten zu können. (Thema Testing)

**Comment by Cavvar** [comment]
@timobunghardt Das ist richtig so. Wir legen aber unseren Fokus momentan darauf, dass eine komplette Einrichtung möglich ist. Dann können wir ohne große Hindernisse die erneute Einrichtung implementieren. Ich erstelle mal für die genannte Funktionalität einen eigenen Issues.

**Comment by Cavvar** [comment]
Für die komplette **Ersteineinrichtung** fehlt die seperate Einrichtung der Startadresse (falls Geräte Adresse null ist) und die zusätzlichen Zieladressen. Genaure Infos in UC4 und UC6 nachschauen. Diese User Story wird in Sprint 3 weitergeführt.

**Comment by SchredlAar** [comment]
Das Benutzerkonto kann nun komplett eingerichtet werden.
