### ISSUE TITLE
Vorname eingeben (UC 3)

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#20]

**Comment by Cavvar** [comment]
|Name der User Story|  User Story | Akzeptanzkriterien|
|--|--|--|
|Vorname eingeben (UC 3)  |  Als Nutzer*in soll der Skill in der Lage sein, mich mit meinem Vornamen ansprechen zu können. Es ist aber auch möglich, hier einen fiktiven Namen anzugeben.| <ul><li>Vorname wird in lokaler Variable oder persistent gespeichert</li></ul>|

**Comment by Cavvar** [comment]
Funktionalität wurde erfolgreich getestet. Nach erneutem Start von Alexa wurde man mit dem Vornamen begrüßt (falls gespeichert)
