### ISSUE TITLE
Heimatadresse und Startstation einrichten (UC 4)

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#21]

**Comment by Cavvar** [comment]
|Name der User Story|  User Story | Akzeptanzkriterien|
|--|--|--|
|Heimatadresse und Startstation einrichten (UC 4)  | Als Nutzer*in kann ich dem Alexa-Skill nach Aufforderung oder per GPS-Ermittelung meine Heimatadresse mitteilen und diese benennen um später bei der Frage nach der aktuellen Route, die Benutzereingabe kurz zu halten. Des Weiteren wird dem Nutzer/der Nutzerin die Möglichkeit gegeben eine Startstationen aus drei auszusuchen, welche anhand GPS ermittelt werden.| <ul><li>Stabile Internetverbindung</li><li>Here-API/GPS-Signal steht zum Zeitpunkt der Einrichtung zur Verfügung</li><li>Heimatadresse wird in lokaler Variable oder persistent gespeichert</li><li>Name der Heimatadresse wird in lokaler Variable oder persistent gespeichert</li><li>Startstation wird in lokaler Variable oder persistent gespeichert</li></ul>|

**Comment by TobiasKuch** [comment]
Die Startstation wird nicht umgesetzt, da die benutzte Startstation je nach Ziel unterschiedlich ist, deswegen ist dieser Slot irrelevant.

**Comment by Cavvar** [comment]
Die Einrichtung der Startadresse/Heimadresse wurde in diesem Sprint 2 mittels Auslesen der Geräte Adresse realisiert. Falls keine Geräte Adresse vorhanden ist, fehlt noch seperate Einrichtung der Startadresse/Heimadresse. Daher wird diese User Story im nächsten Sprint weitergeführt.

**Comment by SchredlAar** [comment]
Es ist nun die komplette Einrichtung der Startadresse möglich
