### ISSUE TITLE
Bevorzugtes Transportmittel eingeben (UC 5)

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#22]

**Comment by Cavvar** [comment]
|Name der User Story|  User Story | Akzeptanzkriterien|
|--|--|--|
|Bevorzugtes Transportmittel eingeben (UC 5)  | Als Nutzer*in kann ich mit einfacher Spracheingabe mein präferiertes Transportmittel eingeben. Diese Eingabe wird bei der späteren Routenberechnung beachtet.| <ul><li>Das bevorzugte Transportmittel wird in lokaler Variable oder persistent gespeichert</li></ul>|

**Comment by TobiasKuch** [comment]
In der hereApi kann man kein bevorzugtes öffentliches Verkehrsmittel wählen, sonder nur komplett auschließen, was ich eher weniger sinnvoll finde.

**Comment by SinaLosi** [comment]
Okay, gibt es irgendeine andere Möglichkeit das abzufragen bzw. wie würde das mit der hereApi dann funktionieren? Es ist ja nur wichtig für die erste Haltestelle, die man von Zuhause aus nutzt. Damit nicht die nächste S-Bahn-Haltestelle angezeigt wird, wenn ich lieber mit dem Bus fahre. Würde es gehen, wenn man die Info in dem Benutzerprofil hinterlegt?

**Comment by TobiasKuch** [comment]
Da die hereApi diese Möglichkeit nicht hat, werden wir dieses Feature nicht umsetzen
