### ISSUE TITLE
Zieladresse und Zielstation einrichten (UC 6)

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#23]

**Comment by Cavvar** [comment]
|Name der User Story|  User Story | Akzeptanzkriterien|
|--|--|--|
|Zieladressen und Zielstationen einrichten (UC 6)  | Als Nutzer*in will ich dem Skill Zieladressen und Zielstationen mitteilen, damit bei der späteren Routenberechnung eine einfache Aufforderung zum Start der Suche ausreichend ist.| <ul><li>Stabile Internetverbindung</li><li>Here-API/GPS-Signal steht zum Zeitpunkt der Einrichtung zur Verfügung</li><li>Zieladressen werden in lokalen Variablen oder persistent gespeichert</li><li>Namen der Zieladressen werden in lokalen Variablen oder persistent gespeichert</li><li>Zielstationen werden in lokalen Variablen oder persistent gespeichert</li></ul>|

**Comment by Cavvar** [comment]
Die Einrichtung **einer** Zielstation und dessen Benennung ist möglich. Die Koordinaten werden hinter dem benutzerdefinierten Namen in DynamoDB gespeichert.
Da der Product Owner die Hinterlegung mehrerer Zieladressen erwünschen, wird diese User Story in Sprint 3 weitergeführt.

**Comment by SchredlAar** [comment]
Es ist nun die Einrichtung von bis zu drei Zielstationen möglich
