### ISSUE TITLE
Nächste Fahrt zu Zieladresse erfragen (UC 7)

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#24]

**Comment by Cavvar** [comment]
|Name der User Story|  User Story | Akzeptanzkriterien|
|--|--|--|
|Nächste Fahrt zu Zieladresse erfragen (UC 7)  | Als Nutzer möchte ich nach erfolgreicher Einrichtung des Benutzerprofils, die nächste Fahrt zum gewünschten Ziel erfragen können. Der Alexa-Skill untersucht mittels Schnittstelle und dem vorhandenen Benutzerprofil die aktuelle Verkehrslage und teilt dem Nutzer die effektivste Route mit.| <ul><li>Stabile Internetverbindung</li><li>Here-API/GPS-Signal steht zum Zeitpunkt der Einrichtung zur Verfügung</li></ul>|

**Comment by SchredlAar** [comment]
Es ist nun möglich eine Route zu einer der gespeicherten Adressen zu erfragen.
Alexa antwortet dem User daraufhin, mit der letzten möglichen Zeit, in der der User noch rechtzeitig an seinem Ziel ankommen kann.
