### ISSUE TITLE
Aufruf Hilfefunktion (UC 8)

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#25]

**Comment by Cavvar** [comment]
|Name der User Story|  User Story | Akzeptanzkriterien|
|--|--|--|
|Aufruf Hilfefunktion (UC 8)  | Als Nutzer will ich, dass der Skill eine Hilfefunktion hat, der mir vor allem bei der Einrichtung des Benutzerprofils beiseite steht.||

**Comment by Cavvar** [comment]
Die User Story kann aufgeteilt werden in folgende Elemente:
- [x] Aufruf der Hilfefunktion
- [ ] Frage nach Informationen zur Zieladresse
- [ ] Frage nach Informationen zur Heimadresse
- [ ] Erhalten der Informationen zur Zieladresse
- [ ] Erhalten der Informationen zur Heimadresse

**Comment by Heusini** [comment]
Erfolgreich getestet.
