### ISSUE TITLE
Dynamo Dresden 

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#26]
Dynamo-DB: Speicherung von Variablen in einer Datenbank

**Comment by Heusini** [comment]
Tests erfolgreich

**Comment by SchredlAar** [comment]
Datenbankanbindung für den Guidelines-Skill per DynamoDB.
Ablauf: Folgen des Moodle-Tutorials

**Comment by Cavvar** [comment]
Wenn nach Start des Skills etwas eingegeben wird, dass keinen Intent aufrufen würde, dann wird der vorhandene Name überschrieben. Deswegen Issue reopened

**Comment by SchredlAar** [comment]
Der Bug wurde gefixt

**Comment by SchredlAar** [comment]
![datenbankanbindung](https://user-images.githubusercontent.com/43880777/49222723-f135f500-f3dc-11e8-9e52-3c4b8d2cc853.png)

**Comment by SchredlAar** [comment]
Diagramm zur Visualisierung der Datenbankanbindung
