### ISSUE TITLE
Vorname auslesen

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#27]

**Comment by SchredlAar** [comment]
User-Story:
Auslesen des Vornamens aus der DynamoDB.
Voraussetzung: Der Vorname wurde vorher bei der Einrichtung gespeichert.

**Comment by Cavvar** [comment]
Funktionalität wurde überprüft. Der Vorname wird ausgelesen, wenn einer in der Datenbank vorhanden ist
