### ISSUE TITLE
hereApi Utility Klasse

### ISSUE THREAD

**Issue by TobiasKuch** [sweIhm-ws2018-19/skillproject-fr-31#28]

**Comment by SchredlAar** [comment]
Diese Klasse dient dazu, aus einer Adresse die zugehörigen Stationen von öffentlichen Verkehrsmitteln zu finden.  Diese Stationen werden dann in der Routenplanung berücksichtigt.

**Comment by SchredlAar** [comment]
![images/HereApi.svg](images/HereApi.svg)
