### ISSUE TITLE
Eigener Alexa Straßen Slot Typ

### ISSUE THREAD

**Issue by Heusini** [sweIhm-ws2018-19/skillproject-fr-31#29]
Erstellen eines eigenen Alexa slot Types
Slot Typen für Stadt und Postleitzahl sind bereits vorhanden.

**Comment by SchredlAar** [comment]
Eigene Types für Straße, Postleitzahl und Hausnummer erstellt

**Comment by SchredlAar** [comment]
Es wurde ein DE-Straßentyp eingeführt.
Ein eigener Typ ist nun hinfällig.
