### ISSUE TITLE
Timer / Alexa Wake up zum Start der erfragten Route

### ISSUE THREAD

**Issue by timobunghardt** [sweIhm-ws2018-19/skillproject-fr-31#30]
Nach der erfragten Routen-Startzeit soll Alexa einen Timer setzen können, der zum gewünschten Zeitpunkt an den Aufbruch erinnert. Der Nutzer soll entscheiden können, ob er den Timer setzen möchte.

**Comment by SchredlAar** [comment]
Issue wird geschlossen, da diese Funktion nicht implementiert wird.
