### ISSUE TITLE
Überschreibung des vorhandenen Benutzerprofil

### ISSUE THREAD

**Issue by Cavvar** [sweIhm-ws2018-19/skillproject-fr-31#31]
Der User bekommt zum Start des Skills die Möglichkeit, sein vorhandenes Benutzerprofil zu überschreiben.

**Comment by Cavvar** [comment]
Der Seb hat diese Funktion implementiert. Der User ist in der Lage, das vorhandene Benutzerprofil zu überschreiben. Finale Test sind noch notwendig

**Comment by SchredlAar** [comment]
Die gespeicherte Einrichtung kann nun komplett gelöscht werden und mit einer neuen überschrieben werden
