### ISSUE TITLE
Uebungsblatt 02 Aufgabe 4

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#5]

**Comment by SchredlAar** [comment]
Es wäre zur Überprüfung bereit

**Comment by Cavvar** [comment]
Die Positionierung der Aktionen macht Sinn. Da ich leider ein Laie bin was das fotografieren angeht, habe aber doch eine Frage.
Macht es nicht Sinn bevor man den Auslöser drückt, die ganzen Einstellungen vorzunehmen? Ist vielleicht keine relevante Frage.

**Comment by SchredlAar** [comment]
Ja ich kenne mich da auch nicht aus aber ich denke die Einstellungen werden vorgenommen nachdem man auf den Auslöser gedrückt hat. Das geht ja schnell

**Comment by Cavvar** [comment]
Dann würde auch sagen das es passt
