### ISSUE TITLE
Übungsblatt 2 Aufgabe 7

### ISSUE THREAD

**Issue by SchredlAar** [sweIhm-ws2018-19/skillproject-fr-31#8]
Ich glaube bei der 7 passen die Zuordnungen nicht ganz

**Comment by SchredlAar** [comment]
![aufgabe 7](https://user-images.githubusercontent.com/43880777/47614522-5e363200-daa1-11e8-96c0-9a1683090ee2.png)

**Comment by Cavvar** [comment]
Hab das Bild im Wiki hinzugefügt.

**Comment by Heusini** [comment]
ich denke zwischen den Klassen gehören striche ohne Pfeil aber durchgezogen!?

**Comment by Cavvar** [comment]
In der Form wie sie jetzt hier stehen, werden Abhängigkeiten gezeigt. B hängt von C und D ab bzw. A hängt von B ab.

**Comment by SchredlAar** [comment]
passt
